# Generated by Django 4.0.2 on 2022-02-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('School', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Phone_no', models.IntegerField(max_length=50)),
                ('Date_Of_Birth', models.DateTimeField(max_length=50)),
                ('Year_of_Admission', models.IntegerField(max_length=50)),
                ('Year_of_Graduation', models.IntegerField(max_length=50)),
                ('Field_Of_study', models.CharField(max_length=50)),
                ('Gpa_score', models.IntegerField(max_length=50)),
                ('Proof_of_Gpa', models.FileField(max_length=50, upload_to='')),
                ('Secondary_school_testimony', models.FileField(max_length=50, upload_to='')),
                ('Candidate_image', models.FileField(max_length=50, upload_to='')),
            ],
        ),
    ]
