# Generated by Django 4.0.2 on 2022-02-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='Registration_no',
            field=models.CharField(default=int, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Date_Of_Birth',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Gpa_score',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Phone_no',
            field=models.CharField(max_length=50),
        ),
    ]
