# Generated by Django 4.0.2 on 2022-02-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0002_applicant_registration_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=str, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Year_of_Admission',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Year_of_Graduation',
            field=models.IntegerField(),
        ),
    ]
