# Generated by Django 4.0.2 on 2022-02-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0003_applicant_gender_alter_applicant_year_of_admission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=7),
        ),
    ]
