# Generated by Django 4.0.2 on 2022-02-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0004_alter_applicant_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('content', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Proof_of_Gpa',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Secondary_school_testimony',
            field=models.FileField(upload_to=''),
        ),
    ]
