# Generated by Django 4.0.2 on 2022-02-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0006_alter_applicant_proof_of_gpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='image')),
                ('name', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
            ],
        ),
    ]
