# Generated by Django 4.0.2 on 2022-02-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0007_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='image')),
            ],
        ),
    ]
