# Generated by Django 4.0.2 on 2022-02-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0008_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog_details',
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.DeleteModel(
            name='team',
        ),
    ]
