# Generated by Django 4.0.2 on 2022-02-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='image')),
                ('content', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
